### ISSUE TITLE
Showing error message if given path does not exist 

### ISSUE THREAD

**Issue by monikkacha** [WarmSaluters/mailmerge-js#12]
I was testing an option to save emails to local storage rather than pushing them to Gmail drafts. I accidentally entered an incorrect path, and it printed emails saved even though the entered path didn't exist.

We should display an error message so that the user knows the path was incorrect.

I am thinking of fixing this issue. What do you think, @charlesyu108

**Comment by charlesyu108** [comment]
Hey, sounds like a good issue! Feel free to open that PR :^)

**Comment by monikkacha** [comment]
@charlesyu108 checks added and PR raised #13

**Comment by charlesyu108** [comment]
Thanks @monikkacha. Sorry for the delay. Just merged and rolled out a new version `mailmerge-js@1.0.23`
