### ISSUE TITLE
Support Non-AI Templating

### ISSUE THREAD

**Issue by charlesyu108** [WarmSaluters/mailmerge-js#9]
We currently support synthesizing/compiling email using an LLM as a template engine. We should also support simple use cases where you might not want to use AI. Engines like Jinja & Nunchucks already exist for this.

Idea: Build an abstractions for a Renderer: `AIRenderer` or `JinjaRenderer`. Switching which one to use will be based on the flag `--model`

**Comment by monikkacha** [comment]
Hey @charlesyu108 

I just checked recent code for local LLM and it looks cool, starting to  work on Nunjucks non-AI feature .

**Comment by monikkacha** [comment]
Hey @charlesyu108 

Facing an issue due to running mailmerge directly from the project, setup operation works as expected but the `compose` operation gives an error about not passing the `contact` option though it's provided in the command. 

Please let me know how do you handle mailmerge operations during development, it might sound silly but working with CLI project first time 😅

![Screenshot 2024-06-12 at 2 24 03 PM](https://github.com/WarmSaluters/mailmerge-js/assets/59527954/438e25ab-75bb-4f59-abf0-d15efc455bd3)

**Comment by charlesyu108** [comment]
> Hey @charlesyu108
> 
> Facing an issue due to running mailmerge directly from the project, setup operation works as expected but the `compose` operation gives an error about not passing the `contact` option though it's provided in the command.
> 
> Please let me know how do you handle mailmerge operations during development, it might sound silly but working with CLI project first time 😅
> 
> ![Screenshot 2024-06-12 at 2 24 03 PM](https://private-user-images.githubusercontent.com/59527954/338895213-438e25ab-75bb-4f59-abf0-d15efc455bd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMjQ4ODUsIm5iZiI6MTcxODIyNDU4NSwicGF0aCI6Ii81OTUyNzk1NC8zMzg4OTUyMTMtNDM4ZTI1YWItNzViYi00ZjU5LWFiZjAtZDE1ZWZjNDU1YmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDIwMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNThlZGI4ZGYwZGI1MzA2OWUyYmZiZmY2ZjMwNmNkMDZkNjVlMWY5NWQ0ZDlkYzc3M2ExOTA0MDUyN2UzOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cedTZjIyaqmgdRGr6ehzegCJEgqGgv1qRWcKaPobl4)

Ah, gotcha. If you are running with `npm start` you'll need to pass `--` in between the args otherwise, `npm` treats the flags as args to `npm`, so: ```npm start  -- compose --contacts ./example/sample-contacts.csv ./examples/outreach-template.md```

**Comment by monikkacha** [comment]
Thanks for the help man, Nunjucks engine added and raised PR #11 , let me know if any changes required .

**Comment by charlesyu108** [comment]
> Thanks for the help man, Nunjucks engine added and raised PR #11 , let me know if any changes required .

Thanks! Super fast. 1 small change requested but otherwise looks great!
